### ISSUE TITLE
Cleanup after we drop support for Python 3.6

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [PyCQA/pylint#4683]
When we do drop support because 3.6 has reached its end of life, we'll need to do some cleanup:

- [x] remove the code for Python 3.6 only and `PY36_PLUS` conditionals
- [x] clean up the minimum required version in the tests and functional tests RC files (this has not been done previously) 
- [x] Use postponed evaluation of annotations (with from ``__future__`` import annotations) -> #6326
- [x] Use dataclasses to simplify the code where it makes the most sense
- [x] Bump `py-version` in `pylintrc` -> #6326
- [ ] Look at coverage drop in https://github.com/PyCQA/pylint/pull/5921 and remove dead code > #6421

**Comment by cdce8p** [comment]
With the removal, we could also start using features that have been added in `3.7`
The most relevant to us IMO would be:
- Postponed evaluation of annotations (with `from __future__ import annotations`)
- Dataclasses

https://www.python.org/downloads/release/python-370/
https://docs.python.org/3.7/whatsnew/3.7.html#new-features

**Comment by cdce8p** [comment]
Just for reference: #4310 (Issue discussing when the removal of 3.6 should happen)

**Comment by Pierre-Sassoulas** [comment]
Thank for the suggestion I added postponed evaluation to the list. Regarding dataclasses, could you explain the advantages compared to keeping NamedTuple for example ?

**Comment by cdce8p** [comment]
Dataclasses are essentially just classes. So compared to `NamedTuple` you can change attributes without creating a new instance of it. Where dataclasses really shine is for classes that just implement some boilerplate code (`__init__` to assign all attributes to instance attrs, basic `__str__`, `__repr__`, `__eg__`, ...). Basically, they are meant for classes that mostly store data (hence the name). https://docs.python.org/3/library/dataclasses.html

Good examples where to use it can be found in the PR for the Similarity checker. 
https://github.com/PyCQA/pylint/blob/65a20b6c5075e1f1756c1e6033c20b289b6edbbf/pylint/checkers/similar.py#L97-L114

https://github.com/PyCQA/pylint/blob/65a20b6c5075e1f1756c1e6033c20b289b6edbbf/pylint/checkers/similar.py#L163-L189

**Comment by Pierre-Sassoulas** [comment]
I added dataclasses to the list :) I think it should be done in good intelligence though (ie: not everywhere for refactor's sake)

**Comment by cdce8p** [comment]
> I added dataclasses to the list :) I think it should be done in good intelligence though (ie: not everywhere for refactor's sake)

Yeah, I completely agree. The initial list was more meant to show which new features we can take most advantage of with `3.7` as min requirement not necessarily that we should refactor old code because of it.

**Comment by DanielNoord** [comment]
@cdce8p Is your typing upgrade tool ready to use for `pylint`? Or will its default value of `3.8` be problematic for us (making it easier to do everything by hand)?

**Comment by cdce8p** [comment]
> @cdce8p Is your typing upgrade tool ready to use for `pylint`? Or will its default value of `3.8` be problematic for us (making it easier to do everything by hand)?

I just released a new version `0.4.0` which also added an option for 3.7: `--py37-plus`. Form a quick test, it looks like it's good to go. It's probably best to add it as a temporary `pre-commit` hook. At least that's the easiest way I found.
```yaml
  - repo: https://github.com/cdce8p/python-typing-update
    rev: v0.4.0
    hooks:
      - id: python-typing-update
        stages: [manual]
        additional_dependencies:
          - "black==22.3.0"
        args:
          - --py37-plus
          - --force
          - --keep-updates
          - --black
        files: ^(pylint)/.+\.py$  # might need to be changed
```
```
pre-commit run --hook-stage manual python-typing-update --all-files
```

**Comment by DanielNoord** [comment]
I'll take a look at this after `argparse` migration is finished!

**Comment by Pierre-Sassoulas** [comment]
I'm for using the pre-commit hook, it's easy to reintroduce ``typing.List`` (could be just habits dying hard). Keeping the hook make sure the code is normalized, the same way we have pyupgrade all the time.

**Comment by DanielNoord** [comment]
I'll add it to the CI action that runs `pre-commit pylint` then. The action is quite slow (sorry Marc 😅) as it essentially runs a bunch of other formatters.

**Comment by cdce8p** [comment]
> The action is quite slow (sorry Marc 😅) as it essentially runs a bunch of other formatters.

The tool wasn't designed to be fast 😄

> I'm for using the pre-commit hook, it's easy to reintroduce `typing.List` (could be just habits dying hard). Keeping the hook make sure the code is normalized, the same way we have pyupgrade all the time.

The pylint typing extension is **much** better for that. -> `consider-using-alias` and `consider-alternative-union-syntax` checks. We just need to update `py-version` for that.
