### ISSUE TITLE
To-do list for release `2.12.1`

### ISSUE THREAD

**Issue by DanielNoord** [PyCQA/pylint#5249]
Might as well create an issue from the [unofficial todo list](https://github.com/PyCQA/pylint/issues/5065#issuecomment-935428793) (hidden in dozen of comment 😄)

_Originally posted by @Pierre-Sassoulas in https://github.com/PyCQA/astroid/pull/1217#discussion_r741786437_

TODO for `2.12.1` (the `python > 3.6.2` release):

- [x] Merge #5068, and #5070
- [x] Remove exception added in #5171
       (included in #5068)
- [x] ~~Release `astroid` `2.8.5` for python > 3.6.2 and remove any `sys.version` guards~~ astroid is still compatible with 3.6.0
- [ ] Release pylint 2.12.1 explicitly for python > 3.6.2
- [x] Handle this comment https://github.com/PyCQA/pylint/pull/5152#issuecomment-960890607
