### ISSUE TITLE
To-do list for release ``2.12.0``

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [PyCQA/pylint#5250]
Might as well create an issue from the [unofficial todo list](https://github.com/PyCQA/pylint/issues/5065#issuecomment-935428793) (hidden in dozen of comment 😄)

_Originally posted by @Pierre-Sassoulas in https://github.com/PyCQA/astroid/pull/1217#discussion_r741786437_

TODO for `2.12.0` (the last `python > 3.6.0` release):

- [x]  telling < 3.6.2 user to upgrade or take 2.9.3 instead. #5171 
- [x]  Release astroid 2.8.5
- [x] Add section to `WhatsNew` mentioning the change #5297
- [x] Release astroid 2.8.6
- [x] ~~Do the last the last `python > 3.6.0` release for astroid https://github.com/PyCQA/astroid/pull/1267~~ (astroid is still compatible with python 3.6.0)
- [x] Release astroid 2.9.0
- [x] If #5336 is merged, upgrade the output of all functional test expected output with their new end column and confidence
- [x] Resolve https://github.com/PyCQA/pylint/pull/5349#discussion_r755315222 #5386
- [ ] Release pylint 2.12.0 as the latest (non) working 3.6.0/3.61 version

**Comment by DanielNoord** [comment]
@Pierre-Sassoulas Do you still want to auto update all expected outputs of the functional tests, to decrease future diffs? Might be good to add it to the todo list if you do.

**Comment by cdce8p** [comment]
> Do you still want to auto update all expected outputs of the functional tests, to decrease future diffs? Might be good to add it to the todo list if you do.

I though it might make sense to do that together with #5336. We should update all message outputs for that anyway.
