### ISSUE TITLE
To-do list for release 2.13.0 

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [PyCQA/pylint#5317]
- [x] #5730
- [x] Refactor the Confidence to be more accurate of what it means see https://github.com/PyCQA/pylint/pull/5369#discussion_r755818326 Done in #5519 
- [x] Release astroid 2.10 and upgrade the version in pylint (#5802)
- [x] 1 issue which needs some further investigation: https://github.com/PyCQA/pylint/issues/5645,
- [x] 1 issue which just need an implementation: https://github.com/PyCQA/pylint/issues/5341
- [x] 1 project maintenance issue: https://github.com/PyCQA/pylint/issues/4701
- [x] 1 project maintenance issue: #5877 
- [x] Another project maintenance issue: https://github.com/PyCQA/pylint/issues/5729
- [x] A lot of issues depending on astroid 2.10.

**Comment by DanielNoord** [comment]
Shall we start the discussion on `check_docs`? The change that deprecated `check_docs` for backward compatibility is 6 years old, see https://github.com/PyCQA/pylint/commit/9423e31126fa2e951d17d1d57d59c1b14bbbd404

Maintaining it is problematic as we can't load the same plugin twice without crashing on the option registering. The change to use `docparams` is also quite easy (just change `check_docs` to `docparams` in your rcfile).

I would vote in favour of removing.

**Comment by Pierre-Sassoulas** [comment]
> I would vote in favor of removing.

Same here, I think it's pretty safe to do at this point.

**Comment by DanielNoord** [comment]
I'm thinking about moving this to 2.14 because of the amount of work involved and the number of duplicate issues we must handle that are already fixed in main and could be released :)

_Originally posted by @Pierre-Sassoulas in https://github.com/PyCQA/pylint/issues/5466#issuecomment-1035517869_

Just my two cents about `2.13`:
Looking at open issues and PRs for `2.13`:
1) There are 4 PRs which are in final stages of review and should be mergeable if we all get together and review and iterate on them
2) 3 issues which needs some further investigation: #5408, #5645,
3) 3 issues which just need an implementation: #5341, #5466 (my proposed hack), #5670
4) 2 project maintenance issues: #4701, #5729
5) A lot of issues depending on `astroid` `2.10`.

From `pylint`'s side that's actually quite manageable, although these are all issues that are less likely to attract contributors due to their difficulty.
If anything focus should probably be on `astroid` `2.10` and trying to clear or move some of the backlog there. There are 6 opens PRs, one of which is a crash, that depend on it.

**Comment by Pierre-Sassoulas** [comment]
> If anything focus should probably be on astroid 2.10 

👍

**Comment by michael-k** [comment]
> If anything focus should probably be on astroid 2.10

Now that this has been resolved in #5802, is there anything blocking a 2.13 release?

**Comment by Pierre-Sassoulas** [comment]
No, we "only" need to handle the list of remaining issues in the milestone.
