### ISSUE TITLE
Todo/to-do list for 2.15.0

### ISSUE THREAD

**Issue by DanielNoord** [PyCQA/pylint#6632]
TODO:
- [x]  Fix any outstanding `TODO: 2.15:` comments
- [x] Integrate latest astroid patch
- [x] Revert #7244 
Opening this now to track discussion on our next major release.

**Comment by DanielNoord** [comment]
One of the things I would like to discuss is to reserve the milestone for actual user-facing changes. I just had a look at the [2.14 milestone](https://github.com/PyCQA/pylint/milestone/55) and it's closed tab is actually pretty unusable. I have done this myself as well, but by adding all changes to documentation and our CI runs it's not actually clear what real changes were made to the code/functionality.

Obviously there will always be a balance somewhere, but I would like to propose to only add new functionality, bug fixes or refactors of actual code into the milestone. If people want to see all commits between `2.13.0` and `2.14.0` they can use `git` to tell then.

**Comment by Pierre-Sassoulas** [comment]
Regarding user-facing or not in #5728, I'd like to separate clearly what is user facing from what is useful only for pylint's devs. I'm going to enforce a regex, maybe the current ``(\*\s[\S[\n  ]+?]*\n\n\s\s(Refs|Closes)) #\d{1,5}`` maybe something with only the PR in parenthesis like black ``* yadayada on a single line (#6632)`` (I think changing the style of the release notes makes sense as the PR will be linked to the issues anyway, and it's easier to check that the PR number is in the whats'new because we have access to it from the CI). It's still a work in progress but I can push the draft if you're interested. 

Regarding the milestone, I'm using it as a big todo list to see what still need to be done. I think it's a good thing to have every issue/PR from a version to be in the milestone. It's possible to check what you want to check by excluding label or requiring labels for example this indicate that we have currently 136 meaningful issue in 2.14 : https://github.com/PyCQA/pylint/issues?q=is%3Aclosed+milestone%3A2.14.0+-label%3A%22Documentation+%F0%9F%93%96%22+-label%3Adependency+-label%3AMaintenance 

The way to do that is at the bottom of the label list in the interface.

![filtering labels](https://user-images.githubusercontent.com/5493666/168763474-3ac7a160-7bad-4951-8fae-9ea41968dda5.png)

**Comment by DanielNoord** [comment]
> I'd like to separate clearly what is user facing from what is useful only for pylint's devs.

👍 

> Regarding the milestone, I'm using it as a big todo list to see what still need to be done.

I like to do this as well for issues, but for some PRs it doesn't make a lot of sense.

> I think it's a good thing to have every issue/PR from a version to be in the milestone.

Imo, changes to the documentation are not "from a version".  We don't include the `doc` directory in our builds and I think they exist separately to the actual program. Same goes for dependency upgrades in our (pre-commit) toolchain. 
I think the milestone can help outside users/developers get a quick overview of everything that went into a release without knowing all our labels and project management specifics. (I often look at project's milestone to see what was done in the latest release when browsing repo's) However, in our project that is no longer possible without knowing our labels.

Since the issue/PR interface doesn't show closed milestone this is also not really user-friendly.

But if you don't agree then let's keep putting everything in the milestone.

**Comment by Pierre-Sassoulas** [comment]
Maybe not maintenance as it's often refactor that touch the code ?

**Comment by DanielNoord** [comment]
> Maybe not maintenance as it's often refactor that touch the code ?

Yeah like I said, I think those are often grey areas where we'll need to find a balance. For example: a PR that adds copyright notices to all files or that reshuffles test files is not really something that is part of a "version" I think. Refactoring to use `argparse` instead of `optparse` is though, even if all of these don't get a changelog entry.

**Comment by Pierre-Sassoulas** [comment]
Alright, I'm going to enforce the need to have a changelog entry according to the label on an issue.
So "documentation", "dependency" and "maintenance" should be exempted... except if they've been added to the current milestone. The decision of changelog or not will be taken by maintainers when assigning label / milestone to a pull request.

**Comment by jacobtylerwalls** [comment]
From discussion on a recent astroid PR:
> There's two issues left in 2.12, including this one that is mergeable, should we even release 2.11.7 ?

@Pierre-Sassoulas fine with me to skip it! We could also probably skip pylint 2.14.5 then.

How's this sound?
- [ ] release 2.12 with PyCQA/astroid#1189 
- [ ] work on pylint compatibility with astroid 2.12 and python 3.11
- [ ] freeze pylint 2.15 (don't add more to the milestone)
- [ ] evaluate milestone, bumping harder things to 2.16 (will much easier with a bunch of astroid stuff cleared out)
- [ ] release 2.15

**Comment by Pierre-Sassoulas** [comment]
Sounds good !

> work on pylint compatibility with astroid 2.12 and python 3.11

Not sure if possible yet as we rely on ``dill`` being compatible with 3.11 (I'm fine with pylint 2.15 not being compatible with python 3.11)

**Comment by jacobtylerwalls** [comment]
Regarding PyCQA/astroid#1189 I reread Marc's review comment and refers to intending to do a "subsequent" review, so I'm wondering if we're better off releasing 2.12 right now and getting on with clearing the Pylint PRs. Tomorrow's another day.

**Comment by Pierre-Sassoulas** [comment]
I'm on mobile at the moment because my pylint/astroid setup died yesterday, if someone want to release astroid 2.11.7 / 2.12.0 using ``doc/release.md``, I would be glad. I don't know how long it will take to get back to normal right now.

**Comment by DanielNoord** [comment]
`2.12` was just released.

@jacobtylerwalls Do you want to see what problems arise when we use it in `pylint` `2.15`? 😄

**Comment by jacobtylerwalls** [comment]
@DanielNoord Up for a `2.12.1`?

**Comment by Pierre-Sassoulas** [comment]
I have a new setup, I'll do it.  See https://github.com/PyCQA/astroid/pull/1698

**Comment by jacobtylerwalls** [comment]
Ring ring! What do you say, is it release time? :bell:

I think we should bump everything (and I mean everything) that's not already got an approving review to the next minor version, and then release this week.

- [ ] astroid 2.12.3 with https://github.com/PyCQA/astroid/pull/1742
- [ ] bump astroid to 2.12.3 in pylint
- [ ] merge any test PRs depending on 2.12.3
- [ ] that's it, release 2.15 (optionally with a pre-release, but no one tested it last time that I recall?)

We can support Python 3.11 in a patch update anyway. Or in 2.16 if we target midfall (makes sense also if 2.15 is going out end of August.) `dill` can keep taking their time.

**Comment by DanielNoord** [comment]
I have done some project maintenance on the milestone.
@Pierre-Sassoulas There are a number of issues where you added the `2.15` milestone. For some I could determine why but there are still some where I don't understand why they are in the milestone. Could you have a look?

@jacobtylerwalls Would you mind putting https://github.com/PyCQA/astroid/pull/1749 in as well? The code was already approved by Pierre, it just needed a test which I just added. I cherry picked all other PRs already.

I have also added `bump TODOs` to your check list. There is one in the codebase which should be bumped to `3.x` I think.

**Comment by Pierre-Sassoulas** [comment]
Sure, I'll have a look. Some issue I labelled 2.15 so we take a decision but it can be delayed to later (we just need to take a decision at some point and not let the issue rot).

**Comment by Pierre-Sassoulas** [comment]
I released and I'm trying to upgrade astroid in pylint in https://github.com/PyCQA/pylint/pull/7333

**Comment by Pierre-Sassoulas** [comment]
Opened https://github.com/PyCQA/pylint/pull/7345

**Comment by Pierre-Sassoulas** [comment]
Seems like the only MR that needed an astroid update in 2.15.0 is https://github.com/PyCQA/pylint/pull/7333

**Comment by jacobtylerwalls** [comment]
> Seems like the only MR that needed an astroid update in 2.15.0 is https://github.com/PyCQA/pylint/pull/7333

That makes sense, since we're just going from patch to patch.

**Comment by Pierre-Sassoulas** [comment]
I've done some cleanup if the milestone there's 1 issue left now. Should we wait or investigate on https://github.com/PyCQA/pylint/issues/6986 or remove it from the milestone too ?

**Comment by DanielNoord** [comment]
@Pierre-Sassoulas I have some time right now. I'll do a quick investigation and come back in an hour if I can't fix it easily.

**Comment by Pierre-Sassoulas** [comment]
Remaining to review/approve before release:
- [ ] #7354 for #5237
- [ ] #7356 (This one's primer can't work, we need to merge as is)
- [ ] #7355
